per_listener_settings true

# MQTT, anonymous
listener 1883 0.0.0.0
allow_anonymous true
set_tcp_nodelay true

# MQTT, password
listener 1884 0.0.0.0
acl_file /mosquitto/config/acl
password_file /mosquitto/config/passwd
set_tcp_nodelay true

# MQTT over TLS, anonymous
listener 8883 0.0.0.0
allow_anonymous true
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
set_tcp_nodelay true

# MQTT over TLS with client certificates
listener 8884 0.0.0.0
require_certificate true
use_identity_as_username true
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
set_tcp_nodelay true

# MQTT over TLS with username/password
listener 8885 0.0.0.0
acl_file /mosquitto/config/acl
password_file /mosquitto/config/passwd
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
tls_version tlsv1.2
set_tcp_nodelay true
